[makefile]
extensions = mk,mak
file_matches = ^((GNU|BSD)?makefile(\..*)?)$
line_comment_tokens = #
string_delims = ",',`
flow = ifeq,ifneq,ifdef,ifndef,else,endif,include
keywords = define,endef,export,override,private,unexport,vpath,phony
return_keywords = return
